Iter5
ShadyZiedan/metrica pull request #5
Opened 2024-01-16 00:50 UTC by ShadyZiedan

Adding environment variables

2024-01-17 10:09 UTC, Nikscorp requested changes
Привет!

Хорошая работа, код в целом мне понравился, но пока принять не могу, замечания оставил в ишью, прошу исправить.

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +	c := make(chan os.Signal, 1)
а кто и когда в этот канал запишет?)

Видимо тут имелось в виду, что еще будет вызов `signal.Notify`, но тогда graceful shutdown-а не получится.

Лучше предварительно сделать `signal. NotifyContext`, передать данный контекст в горутины, читая его Done в них в цикле в select-e вместе с time.After.

Сами горутины же дожидаться по waitgroupе

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +type Config struct {
лучше вынести все это в отдельный пакет

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +func reportCollect(baseURL string, reportInterval int, mc *services.MerticsCollector) {
это точно должно быть в отдельном пакете, в cmd должна быть только инициализация структур слоев и запуск основного метода агента, условный `agent.Run(...)`

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +			return err
ошибки стоит всегда врапать, иначе теряется ее контекст (не путать с сошным context)

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +		metrics := mc.Collect()
а почему collect делается и в report-е и в poll-collect-е?

2024-01-17 10:09 UTC, Nikscorp commented on cmd/agent/main.go
> +	c := make(chan os.Signal, 1)
в первом спринте допускается не использовать конкаренси и все делать в основной горутине. Если будешь их оставлять — нужно также избавиться от рейсов (они тут есть)

2024-01-17 10:09 UTC, Nikscorp commented on cmd/server/main.go
> +type Config struct {
пирсинг флагов лучше вынести в отдельный пакет

2024-01-17 10:09 UTC, Nikscorp commented on internal/server/storage/mem_storage.go
> +	m       sync.Mutex
кажется лучше rw mutex

2024-01-17 10:09 UTC, Nikscorp commented on internal/server/storage/mem_storage.go
> +	metrics := make([]*models.Metric, 0, len(s.storage))
- тут тоже нужно лечить мьютекс на чтение
- в exp есть maps.Keys https://pkg.go.dev/golang.org/x/exp/maps#Keys

2024-01-17 10:09 UTC, Nikscorp commented on internal/server/storage/metrics_repository.go
> +type MetricsRepository interface {
в go интерфейсы обычно объявляют на стороне консьюмера https://go.dev/wiki/CodeReviewComments#interfaces

2024-01-17 10:09 UTC, Nikscorp commented on internal/server/storage/mem_storage.go
> +		return nil, errors.New("Couldn't create a metric")
текст ошибки принято писать с маленькой буквы

2024-01-17 10:09 UTC, Nikscorp commented on go.mod
> +go 1.21.5
давай оставим просто 1.21, минорная версия — это слишком жестко

2024-01-17 10:12 UTC, Nikscorp commented on cmd/agent/main.go
> +func reportCollect(baseURL string, reportInterval int, mc *services.MerticsCollector) {
и лучше сразу их сделать методами

2024-01-17 10:22 UTC, Nikscorp commented on internal/server/storage/mem_storage.go
> +		return nil, errors.New("Couldn't create a metric")
ну и скорее это должна быть well-known ошибка объявленная в глобальной переменной

2024-01-18 00:52 UTC, ShadyZiedan commented on internal/server/storage/metrics_repository.go
> +type MetricsRepository interface {
Пробовал обявить на стороне консюмера (internal/server/server.go), и сталкывался с import cycle error в internal/server/handlers/router.go...

2024-01-18 04:21 UTC, Nikscorp commented on internal/server/storage/metrics_repository.go
> +type MetricsRepository interface {
ну так убери просто циклический импорт)

2024-01-18 08:02 UTC, ShadyZiedan commented on internal/server/storage/metrics_repository.go
> +type MetricsRepository interface {
Думаю решил)

2024-01-18 08:42 UTC, Nikscorp requested changes
Привет!

Хорошая работа над замечаниями, добавил еще несколько, буду ждать исправлений.

2024-01-18 08:42 UTC, Nikscorp commented on cmd/agent/config/config.go
> +package config
этот пакет лучше поместить в internal

2024-01-18 08:42 UTC, Nikscorp commented on cmd/server/config/config.go
> +package config
этот тоже лучше в internal

2024-01-18 08:42 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +	pollChan := time.NewTicker(time.Duration(a.PollInterval) * time.Second)
ticker-ы нужно заступать в defer-е

2024-01-18 08:42 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +			a.sendMetricsToServer(metrics)
сюда тоже нужно передавать контекст. Внутри send его еще желательно обернуть в таймаут. Значение тайм-аута задать в именованной константе

2024-01-18 08:42 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +			return err
было бы здорово врапать ошибки, а не просто их возвращать.

`return fmt.Errorf("update gauge '%s'->'%s': %w", metricName, val, err)`

 Актуально для всех строчек вида `return ... err ...`

2024-01-18 08:42 UTC, Nikscorp commented on internal/agent/services/metrics_collector.go
> +type AgentMetrics struct {
сейчас некритично, но кажется лучше сразу инкапсулировать эти мапки, так проще будет конкурентный доступ организовать в будущем

2024-01-18 08:42 UTC, Nikscorp commented on internal/server/handlers/router.go
> +	r.Post(`/update/{metricType}/{metricName}/{metricValue}`, UpdateMetricHandler(repo))
у тебя каждый хэндлер принимает `repo` — это верный признак того, что хэндлеры следует сделать структурой одного метода — тогда и замыкание будет не нужно.

2024-01-18 08:42 UTC, Nikscorp commented on internal/repositories/metrics_repository.go
> +type MetricsRepository interface {
ну имелось в виду прям в пакете handlers его описать как приватный интерфейс.

Представь, что у тебя будет несколько сервисов, каждый будет использовать сабсет методов этого репозитория — так же куда проще отслеживать зависимости будет.

Удали просто строку `var _ repositories.MetricsRepository = (*MemStorage)(nil)` — и тебя не будет никаких проблем, соответствие интерфейсу у тебя и так будет проверяться при компиляции

2024-01-19 16:17 UTC, Nikscorp approved these changes
Привет!

Оставил еще несколько замечаний, в основном это то, что мы обсуждали на 1:1.
В целом их исправления тривиальны, а работа уже имеет хороший уровень, поэтому ставлю approve.

Поправь тогда замечания самостоятельно и можно мерджить pr. В случае затруднений — пиши в пачку.

Повторно отправлять этот pr на ревью не надо.
Ставлю аппрув и засчитываю работу.

2024-01-19 16:17 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +			_, err := a.Client.R().Post(fmt.Sprintf("/update/gauge/%s/%v", metric.Name, metric.Value))
контекст не устанавливается в вызовы клиента. Стоит установить.

2024-01-19 16:17 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +	default:
Чтобы уменьшить вложенность ветку default-а лучше оставить пустой, впрочем этот select тоже можно убрать, так как он учтется клиентом, если его выставить

2024-01-19 16:17 UTC, Nikscorp commented on internal/agent/services/agent_metrics.go
> +	var gaugeMetrics []GaugeMetric
в подобный местах лучше создавать через make и сразу выставлять capacity, чтобы избежать лишних append-ов

2024-01-19 16:17 UTC, Nikscorp commented on internal/agent/services/agent_metrics.go
> +	return &AgentMetrics{Gauge: newGaugeCollection(), Counter: newCounterCollection()}
такие инициализации лучше делать сразу многострочными кмк

2024-01-19 16:17 UTC, Nikscorp commented on internal/server/handlers/metrics_repository.go
> +type MetricsRepository interface {
можно сделать приватным, в отдельный файл выносить думаю смысла нету

2024-01-19 16:17 UTC, Nikscorp commented on internal/server/storage/mem_storage.go
> +var ErrMetricNotCreated = errors.New("couldn't create a metric")
лучше блоковой определять переменные с похожей семантикой

```go
var (
  // ...
)
```

2024-01-19 22:13 UTC, merged