Iter9
ShadyZiedan/metrica pull request #9
Opened 2024-02-04 16:35 UTC by ShadyZiedan

Adding file storage service

2024-02-05 21:46 UTC, Nikscorp requested changes
Добавил замечания в комментарии к pr.

Плюс также пропущено условие про синхронную запись (то есть append в файл на каждое обновление метрики).

> Флаг -i, переменная окружения STORE_INTERVAL — интервал времени в секундах, по истечении которого текущие показания сервера сохраняются на диск (по умолчанию 300 секунд, значение 0 делает запись синхронной).

2024-02-05 21:46 UTC, Nikscorp commented on cmd/agent/main.go
> +	cnf := config.ParseConfig()
чаще все же conf или cfg

2024-02-05 21:46 UTC, Nikscorp commented on cmd/server/main.go
> +	"os"
импорты не отсортированы, настрой себе в IDE использование goimports по сохранению файла (обычно включено по умолчанию)

2024-02-05 21:46 UTC, Nikscorp commented on cmd/server/main.go
> +	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
стоит добавить еще SIGTERM

2024-02-05 21:46 UTC, Nikscorp commented on cmd/server/main.go
> +	go fileStorageService.Run(ctx)
хочется добавить wait-group-у, чтобы дожидаться его завершения

2024-02-05 21:46 UTC, Nikscorp commented on internal/agent/agent/agent.go
> +		return err
все ошибки стоит wrapp-ать через `fmt.Errorf` добавляя причину их возникновения

2024-02-05 21:46 UTC, Nikscorp commented on internal/server/middleware/request_logger.go
> +	w.responseData.wroteHeader = true
тут тоже правильней через maybeWriteHeader, тк WriteHeader может быть ошибочно вызван после Write-а, например

2024-02-05 21:46 UTC, Nikscorp commented on internal/server/middleware/request_logger.go
> +		duration := time.Duration(0)
просто передавай time.Start в defer и там уже делай time.Since. Иначе при панике получится нулевой duration

2024-02-05 21:46 UTC, Nikscorp commented on internal/server/server/server.go
> +		err := ws.Server.ListenAndServe()
а вот тут стало не очень хорошо. Тк если ListenAndServe сразу вернет ошибку — ты этого не увидишь нигде.

Ошибку стоит возвращать все же из ListenAndServe (можно отфильтровать ErrServerClosed), а shutdown как раз делать в отдельной горутине

2024-02-05 21:46 UTC, Nikscorp commented on internal/server/server/server.go
> +//type Server interface {
если есть неиспользуемый код — удаляй его, а не комментируй

2024-02-05 21:46 UTC, Nikscorp commented on internal/server/services/file_storage_service.go
> +	defer s.fileStorage.Close()
ошибку close-а при записи в файл стоит обрабатывать, а не игнорировать

2024-02-09 00:23 UTC, ShadyZiedan commented on internal/server/middleware/request_logger.go
> +	w.responseData.wroteHeader = true
Пока не очень понятно что надо сделать(

2024-02-09 18:02 UTC, Nikscorp commented on internal/server/middleware/request_logger.go
> +	w.responseData.wroteHeader = true
обсудили на 1-1

2024-02-09 18:05 UTC, Nikscorp approved these changes
Работа принята.

Замечание с синхронным режим остается, но может быть исправлено позже в рамках следующих инкрементов

2024-02-09 18:05 UTC, Nikscorp commented on internal/server/services/file_storage_service.go
> +	if s.conf.StoreInterval == 0 { //Async mode
уже обсудили, что тут реализован async Mode, а надо как раз sync.
Предлагается исправить в рамках следующего инкремента

2024-02-11 16:26 UTC, merged